### PR TITLE
future proof method that is marked for incompatible change

### PR DESCRIPTION
**Pull request by elharo**
and generally be explicit about which dependencies this depends on

### CODE REVIEW

**Comment by elharo** [comment]
Is it useful though? The relevant detail is that the platform default is being used. The point is that whatever value that is, and which we would print here, is not reliable or consistent.

**Comment by dennisl** [comment]
In my experience it is very useful. When moving a project from being built locally by developers to a CI solution, developers are often surprised when they don't get the same results there.

**Comment by elharo** [comment]
Yes, and when that happens they should sit down and figure out which encoding they should use (usually UTF-8). They should not simply copy and paste whichever encoding they happened to be using by accident like they're writing a characterization test to mimic the idiosyncratic behavior of their development box.

**Comment by dennisl** [comment]
If their build is failing, then knowing the encoding that was used gives
them a hint about what not to use.

**Comment by jira-importer** [comment]
Resolve #284

**Pull request merged**
