### PR TITLE
A desperate PR to ask if it is possible to keep this repo relevant by upgrading its (full of CVEs) dependencies please :) 

### PR DESCRIPTION
**Pull request by patpatpat123**
Following this checklist to help us incorporate your 
contribution quickly and easily:

I do not have a Jira account. It is just me trying to bump a pom file using java 7, known to be EOL, and other dependencies that have proven CVEs.
 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MRESOURCES) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without 
       pulling in other changes.

I hope mine is meaningful.
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Format the pull request title like `[MRESOURCES-XXX] - Fixes bug in ApproximateQuantiles`,
       where you replace `MRESOURCES-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the 
       commit message.
 - [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.

Yes, and all tests passed
 - [ ] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will 
       be performed on your pull request automatically.
 - [ ] You have run the integration tests successfully (`mvn -Prun-its clean verify`).

I am actually fine, and even prefer not to be a contributor. I just want to keep this very cool project relevant with security and time
If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [ ] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [ ] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by khmarbaise** [comment]
Please create an JIRA account (register) and create an appropriate issue in JIRA for that...and also check the information about license etc. otherwise we can not accept such a PR..

Changing using `final` does not solve any issue..

Please reread the contribution part in the READ ME file (https://github.com/apache/maven-resources-plugin/blob/master/README.md)...

**Comment by slachiewicz** [comment]
Thank you for pushing us beyond our comfort zone. 
We try to update dependencies - with over 100 sub-projects it can be difficult.

Anyway - thx for the help :)

**Comment by michael-o** [comment]
> Thank you for pushing us beyond our comfort zone. We try to update dependencies - with over 100 sub-projects it can be difficult.
> 
> Anyway - thx for the help :)

It is rather a PITA. An FTE can do updating depencies all day long... :-(

**Comment by patpatpat123** [comment]
Thank you all for the help provided. Wishing you all a very pleasant day

**Pull request closed without merging**
